# Generated by Django 3.2.4 on 2021-06-21 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNascimento', models.DateTimeField()),
                ('foto', models.ImageField(upload_to='fotos_alunos')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numeroTotalAulas', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Matérias',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltas1', models.IntegerField()),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltas2', models.IntegerField()),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltas3', models.IntegerField()),
                ('nota4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('faltas4', models.IntegerField()),
                ('notaFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('idTurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='idTurma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
    ]
