# Generated by Django 3.2.4 on 2021-06-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210621_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='notaFinal',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
