# Generated by Django 3.2.4 on 2021-06-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataNascimento',
            field=models.DateTimeField(),
        ),
    ]
