# Generated by Django 3.2.4 on 2021-06-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aluno_datanascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='aprovado',
        ),
    ]
