# Generated by Django 3.2.4 on 2021-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210621_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='nota1',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota2',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota3',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota4',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notaFinal',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
