# Generated by Django 3.2.4 on 2021-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210623_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='aprovado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='faltas1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='faltas2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='faltas3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='faltas4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notaFinal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
