# Generated by Django 3.2.4 on 2021-06-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210623_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
